# DisplayName: Arctic Frost
format = """\
[](bg:#2E3440 fg:#88C0D0)\
[ ](bg:#88C0D0 fg:#2E3440)\
[](fg:#88C0D0 bg:#81A1C1)\
$directory\
[](fg:#81A1C1 bg:#EBCB8B)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#EBCB8B bg:#2E3440)\
$python\
$nodejs
$character\
"""

[python]
format = '[ $symbol$virtualenv ]($style)'
style = "fg:#B48EAD bg:#2E3440"

[nodejs]
format = '[ $symbol$version ]($style)'
style = "fg:#A3BE8C bg:#2E3440"

[directory]
format = "[  $path ]($style)"
style = "fg:#2E3440 bg:#81A1C1"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:#2E3440 bg:#EBCB8B"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'bold fg:#2E3440 bg:#EBCB8B'
conflicted = ' '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕${ahead_count}⇣${behind_count} '
untracked = ' '
stashed = ' '
modified = '󰷉 '
staged = ' '
renamed = ' '
deleted = ' '
up_to_date = ''

[git_metrics]
format = "([+$added ]($added_style))[]($added_style)([-$deleted ]($deleted_style))"
added_style = "fg:#A3BE8C bg:#EBCB8B"
deleted_style = "fg:#BF616A bg:#EBCB8B"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:#2E3440"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#BF616A) '
