# DisplayName: Rose Garden
format = """\
[](bg:#191724 fg:#EBBCBA)\
[ ](bg:#EBBCBA fg:#191724)\
[](fg:#EBBCBA bg:#F6C177)\
$directory\
[](fg:#F6C177 bg:#9CCFD8)\
$git_branch\
$git_status\
$git_metrics\
[](fg:#9CCFD8 bg:#191724)\
$python\
$nodejs
$character\
"""

[python]
format = '[ $symbol$virtualenv ]($style)'
style = "fg:#C4A7E7 bg:#191724"

[nodejs]
format = '[ $symbol$version ]($style)'
style = "fg:#9CCFD8 bg:#191724"

[directory]
format = "[  $path ]($style)"
style = "fg:#191724 bg:#F6C177"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:#191724 bg:#9CCFD8"

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'bold fg:#191724 bg:#9CCFD8'
conflicted = ' '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕${ahead_count}⇣${behind_count} '
untracked = ' '
stashed = ' '
modified = '󰷉 '
staged = ' '
renamed = ' '
deleted = ' '
up_to_date = ''

[git_metrics]
format = "([+$added ]($added_style))[]($added_style)([-$deleted ]($deleted_style))"
added_style = "fg:#31748F bg:#9CCFD8"
deleted_style = "fg:#EB6F92 bg:#9CCFD8"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:#191724"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#EB6F92) '
